/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutDoctorRouteImport } from './routes/about-doctor'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as MedicinesIndexRouteImport } from './routes/medicines.index'
import { Route as MedicinesSlugRouteImport } from './routes/medicines.$slug'
import { Route as MedicinesCategorySlugRouteImport } from './routes/medicines.category.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDoctorRoute = AboutDoctorRouteImport.update({
  id: '/about-doctor',
  path: '/about-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesIndexRoute = MedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesSlugRoute = MedicinesSlugRouteImport.update({
  id: '/medicines/$slug',
  path: '/medicines/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesCategorySlugRoute = MedicinesCategorySlugRouteImport.update({
  id: '/medicines/category/$slug',
  path: '/medicines/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/account': typeof AccountRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/medicines/': typeof MedicinesIndexRoute
  '/medicines/category/$slug': typeof MedicinesCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/account': typeof AccountRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/medicines': typeof MedicinesIndexRoute
  '/medicines/category/$slug': typeof MedicinesCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/account': typeof AccountRoute
  '/appointments': typeof AppointmentsRoute
  '/auth': typeof AuthRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/services': typeof ServicesRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms': typeof TermsRoute
  '/treatments': typeof TreatmentsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/medicines/$slug': typeof MedicinesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/medicines/': typeof MedicinesIndexRoute
  '/medicines/category/$slug': typeof MedicinesCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-doctor'
    | '/account'
    | '/appointments'
    | '/auth'
    | '/book-appointment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/shipping-policy'
    | '/terms'
    | '/treatments'
    | '/blog/$slug'
    | '/medicines/$slug'
    | '/blog/'
    | '/medicines/'
    | '/medicines/category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-doctor'
    | '/account'
    | '/appointments'
    | '/auth'
    | '/book-appointment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/shipping-policy'
    | '/terms'
    | '/treatments'
    | '/blog/$slug'
    | '/medicines/$slug'
    | '/blog'
    | '/medicines'
    | '/medicines/category/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-doctor'
    | '/account'
    | '/appointments'
    | '/auth'
    | '/book-appointment'
    | '/cart'
    | '/checkout'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/privacy-policy'
    | '/refund-policy'
    | '/services'
    | '/shipping-policy'
    | '/terms'
    | '/treatments'
    | '/blog/$slug'
    | '/medicines/$slug'
    | '/blog/'
    | '/medicines/'
    | '/medicines/category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutDoctorRoute: typeof AboutDoctorRoute
  AccountRoute: typeof AccountRoute
  AppointmentsRoute: typeof AppointmentsRoute
  AuthRoute: typeof AuthRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ServicesRoute: typeof ServicesRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsRoute: typeof TermsRoute
  TreatmentsRoute: typeof TreatmentsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  MedicinesSlugRoute: typeof MedicinesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  MedicinesIndexRoute: typeof MedicinesIndexRoute
  MedicinesCategorySlugRoute: typeof MedicinesCategorySlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-doctor': {
      id: '/about-doctor'
      path: '/about-doctor'
      fullPath: '/about-doctor'
      preLoaderRoute: typeof AboutDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/': {
      id: '/medicines/'
      path: '/medicines'
      fullPath: '/medicines/'
      preLoaderRoute: typeof MedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/$slug': {
      id: '/medicines/$slug'
      path: '/medicines/$slug'
      fullPath: '/medicines/$slug'
      preLoaderRoute: typeof MedicinesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/category/$slug': {
      id: '/medicines/category/$slug'
      path: '/medicines/category/$slug'
      fullPath: '/medicines/category/$slug'
      preLoaderRoute: typeof MedicinesCategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutDoctorRoute: AboutDoctorRoute,
  AccountRoute: AccountRoute,
  AppointmentsRoute: AppointmentsRoute,
  AuthRoute: AuthRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ServicesRoute: ServicesRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsRoute: TermsRoute,
  TreatmentsRoute: TreatmentsRoute,
  BlogSlugRoute: BlogSlugRoute,
  MedicinesSlugRoute: MedicinesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  MedicinesIndexRoute: MedicinesIndexRoute,
  MedicinesCategorySlugRoute: MedicinesCategorySlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
