/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutDoctorRouteImport } from './routes/about-doctor'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as MedicinesIndexRouteImport } from './routes/medicines.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutDoctorRoute = AboutDoctorRouteImport.update({
  id: '/about-doctor',
  path: '/about-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinesIndexRoute = MedicinesIndexRouteImport.update({
  id: '/medicines/',
  path: '/medicines/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/consultation': typeof ConsultationRoute
  '/services': typeof ServicesRoute
  '/treatments': typeof TreatmentsRoute
  '/medicines/': typeof MedicinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/consultation': typeof ConsultationRoute
  '/services': typeof ServicesRoute
  '/treatments': typeof TreatmentsRoute
  '/medicines': typeof MedicinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-doctor': typeof AboutDoctorRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/consultation': typeof ConsultationRoute
  '/services': typeof ServicesRoute
  '/treatments': typeof TreatmentsRoute
  '/medicines/': typeof MedicinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-doctor'
    | '/book-appointment'
    | '/consultation'
    | '/services'
    | '/treatments'
    | '/medicines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-doctor'
    | '/book-appointment'
    | '/consultation'
    | '/services'
    | '/treatments'
    | '/medicines'
  id:
    | '__root__'
    | '/'
    | '/about-doctor'
    | '/book-appointment'
    | '/consultation'
    | '/services'
    | '/treatments'
    | '/medicines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutDoctorRoute: typeof AboutDoctorRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  ConsultationRoute: typeof ConsultationRoute
  ServicesRoute: typeof ServicesRoute
  TreatmentsRoute: typeof TreatmentsRoute
  MedicinesIndexRoute: typeof MedicinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-doctor': {
      id: '/about-doctor'
      path: '/about-doctor'
      fullPath: '/about-doctor'
      preLoaderRoute: typeof AboutDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicines/': {
      id: '/medicines/'
      path: '/medicines'
      fullPath: '/medicines/'
      preLoaderRoute: typeof MedicinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutDoctorRoute: AboutDoctorRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  ConsultationRoute: ConsultationRoute,
  ServicesRoute: ServicesRoute,
  TreatmentsRoute: TreatmentsRoute,
  MedicinesIndexRoute: MedicinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
